"""initial migration

Revision ID: 178c077be2db
Revises: a98c16c6fce2
Create Date: 2025-04-15 22:58:56.874512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178c077be2db'
down_revision: Union[str, None] = 'a98c16c6fce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('dormitories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ad_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ads', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('ads', sa.Column('dormitory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ads', 'dormitories', ['dormitory_id'], ['id'])
    op.create_foreign_key(None, 'ads', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_column('ads', 'dormitory_id')
    op.drop_column('ads', 'category_id')
    op.drop_table('ad_photos')
    op.drop_table('dormitories')
    op.drop_table('categories')
    # ### end Alembic commands ###
