"""initial migration

Revision ID: a98c16c6fce2
Revises: abd981823480
Create Date: 2025-04-15 22:48:17.477129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98c16c6fce2'
down_revision: Union[str, None] = 'abd981823480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ads_dormitory_id_fkey', 'ads', type_='foreignkey')
    op.drop_constraint('ads_category_id_fkey', 'ads', type_='foreignkey')
    op.drop_column('ads', 'category_id')
    op.drop_column('ads', 'dormitory_id')
    op.drop_table('categories')
    op.drop_table('ad_photos')
    op.drop_table('dormitories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('dormitory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ads_category_id_fkey', 'ads', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('ads_dormitory_id_fkey', 'ads', 'dormitories', ['dormitory_id'], ['id'])
    op.create_table('dormitories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dormitories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dormitories_pkey'),
    sa.UniqueConstraint('name', name='dormitories_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ad_photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name='ad_photos_ad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ad_photos_pkey')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('id', name='categories_id_key')
    )
    # ### end Alembic commands ###
