"""initial migration

Revision ID: abd981823480
Revises: 55259e64a486
Create Date: 2025-04-15 22:43:26.704579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd981823480'
down_revision: Union[str, None] = '55259e64a486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_photos', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ad_photos', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ads', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ads', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ads', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ads', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ads', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dormitories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dormitories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ads', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('ads', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ads', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ads', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ads', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ad_photos', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ad_photos', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
